// <auto-generated />
using System;
using Digital_Services_BD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digital_Services_BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220111171206_deliverableComplted")]
    partial class deliverableComplted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Digital_Services_BD.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AddressLineTwo")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("AltMobile")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("City")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LastName")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("State")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Zip")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carousels");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CarouselJoinCarouselImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarouselId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarouselId");

                    b.ToTable("CarouselJoinCarouselImages");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CartProductItemBundle", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemBundleId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CartId", "ProductItemBundleId");

                    b.HasIndex("ProductItemBundleId");

                    b.ToTable("CartProductItemBundles");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Deliverable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliverables");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliverableId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemBundleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliverableId");

                    b.HasIndex("ProductItemBundleId");

                    b.ToTable("DeliverableBundles");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableBundleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliverableBundleId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductStockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliverableBundleId");

                    b.HasIndex("ProductStockId")
                        .IsUnique()
                        .HasFilter("[ProductStockId] IS NOT NULL");

                    b.ToTable("DeliverableBundleItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliverableId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductStockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliverableId");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasFilter("[OrderItemId] IS NOT NULL");

                    b.HasIndex("ProductStockId")
                        .IsUnique()
                        .HasFilter("[ProductStockId] IS NOT NULL");

                    b.ToTable("DeliverableItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.EncryptionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EncryptionKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "DbieFWw3PA6GsnHxBxE8Yzxgk3s4oAcruXDMzfxnOLh3O9bS3M6GcSOsMBPYvwhf",
                            LastUpdated = new DateTime(2022, 1, 11, 17, 12, 5, 298, DateTimeKind.Utc).AddTicks(490)
                        });
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FawIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmEmail")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DeliverableId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsAnonymousOrder")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PromoCodeDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SendOfferInMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxesAndFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductStockId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("ProductStockId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.OrderProductItemBundle", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemBundleId")
                        .HasColumnType("int");

                    b.Property<decimal>("BundleDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BundlePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "ProductItemBundleId");

                    b.HasIndex("ProductItemBundleId");

                    b.ToTable("OrderProductItemBundle");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.PaymentGwConfig", b =>
                {
                    b.Property<short?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiRoot")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CancelCallbackUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Data_a")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_b")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_c")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_e")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailCallbackUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GwName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuccessCallbackUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentGwConfigs");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AmountInUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTrnxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIssuerBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIssuerCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("RateOfUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurjoPayCode")
                        .HasColumnType("int");

                    b.Property<string>("SurjoPayMsg")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SurjoPayOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrnxMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("SurjoPayOrderId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("HowToConsume")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Limitations")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhatCanBeDone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductCategoryJoinProductGroup", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.HasKey("ProductCategoryId", "ProductGroupId");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("ProductCategoryJoinProductGroup");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("HowToConsume")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Limitations")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhatCanBeDone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("HowToConsume")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShippable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Limitations")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhatCanBeDone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BundleDiscount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveNow")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ProductItemBundles");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemBundleJoinProductItem", b =>
                {
                    b.Property<int>("ProductItemBundleId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductItemBundleId", "ProductItemId");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductItemBundleJoinProductItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemCustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductItemCustomFields");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryInfo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Developer")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DownloadSize")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Genre")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Os")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Platform")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RegionCodes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RegionCountries")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequirementCpu")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequirementDisk")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequirementGpu")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequirementRam")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ValidityPeriod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId")
                        .IsUnique();

                    b.ToTable("ProductItemFeatures");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinProductCategory", b =>
                {
                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductItemId", "ProductCategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("ProductItemJoinProductCategory");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinPromoOffer", b =>
                {
                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("PromoOfferId")
                        .HasColumnType("int");

                    b.HasKey("ProductItemId", "PromoOfferId");

                    b.HasIndex("PromoOfferId");

                    b.ToTable("ProductItemJoinPromoOffer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinSearchTagProductItem", b =>
                {
                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("SearchTagProductItemId")
                        .HasColumnType("int");

                    b.HasKey("ProductItemId", "SearchTagProductItemId");

                    b.HasIndex("SearchTagProductItemId");

                    b.ToTable("ProductItemJoinSearchTagProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductItemPrices");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Overview")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ProductSections");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductSectionJoinProductItem", b =>
                {
                    b.Property<int>("ProductSectionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.HasKey("ProductSectionId", "ProductItemId");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductSectionJoinProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuxiliaryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliverableBundleItemId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliverableItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VendorInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("Status");

                    b.ToTable("ProductStocks");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductStockCount", b =>
                {
                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductItemId");

                    b.ToTable("ProductStockCounts");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.PromoOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("CurrencyCountry")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("OfferBeginsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("OfferEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("PromoOffers");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.SearchTagProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("SearchTagProductItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.SmtpConfig", b =>
                {
                    b.Property<short?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("Port")
                        .HasColumnType("smallint");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("UseAuthentication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("UseSecureConnection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SmtpConfigs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Customer", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("BirthDate")
                        .IsUnicode(true)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardNo")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("IdCardType")
                        .HasColumnType("int");

                    b.Property<string>("IdCardVerifyPic")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePicLink")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Address", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Address_CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CarouselJoinCarouselImage", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Carousel", "Carousel")
                        .WithMany("CarouselJoinCarouselImage")
                        .HasForeignKey("CarouselId")
                        .HasConstraintName("FK_CarouselJoinCarouselImage_CarouselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carousel");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CartItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("FK_CartItem_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.CartProductItemBundle", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Cart", "Cart")
                        .WithMany("CartProductItemBundles")
                        .HasForeignKey("CartId")
                        .HasConstraintName("FK_CartJoinProductItemBundle_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItemBundle", "ProductItemBundle")
                        .WithMany("CartProductItemBundle")
                        .HasForeignKey("ProductItemBundleId")
                        .HasConstraintName("FK_CartJoinProductItemBundle_ProductItemBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductItemBundle");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Deliverable", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Order", "Order")
                        .WithOne("Deliverable")
                        .HasForeignKey("Digital_Services_BD.Models.Deliverable", "OrderId")
                        .HasConstraintName("FK_Deliverable_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableBundle", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Deliverable", "Deliverable")
                        .WithMany("DeliverableBundles")
                        .HasForeignKey("DeliverableId")
                        .HasConstraintName("FK_DeliverableBundle_DeliverableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItemBundle", "ProductItemBundle")
                        .WithMany()
                        .HasForeignKey("ProductItemBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverable");

                    b.Navigation("ProductItemBundle");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableBundleItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.DeliverableBundle", "DeliverableBundle")
                        .WithMany("DeliverableBundleItems")
                        .HasForeignKey("DeliverableBundleId")
                        .HasConstraintName("FK_DeliverableBundleItem_DeliverableBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductStock", "ProductStock")
                        .WithOne("DeliverableBundleItem")
                        .HasForeignKey("Digital_Services_BD.Models.DeliverableBundleItem", "ProductStockId")
                        .HasConstraintName("FK_DeliverableBundleItem_ProductStockId");

                    b.Navigation("DeliverableBundle");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Deliverable", "Deliverable")
                        .WithMany("DeliverableItems")
                        .HasForeignKey("DeliverableId")
                        .HasConstraintName("FK_DeliverableItem_DeliverableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.OrderItem", "OrderItem")
                        .WithOne("DeliverableItem")
                        .HasForeignKey("Digital_Services_BD.Models.DeliverableItem", "OrderItemId")
                        .HasConstraintName("FK_DeliverableItem_OrderItemId");

                    b.HasOne("Digital_Services_BD.Models.ProductStock", "ProductStock")
                        .WithOne("DeliverableItem")
                        .HasForeignKey("Digital_Services_BD.Models.DeliverableItem", "ProductStockId")
                        .HasConstraintName("FK_DeliverableItem_ProductStockId");

                    b.Navigation("Deliverable");

                    b.Navigation("OrderItem");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Order", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId");

                    b.HasOne("Digital_Services_BD.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Order_CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.OrderItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderItem_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany()
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductStock", "ProductStock")
                        .WithMany()
                        .HasForeignKey("ProductStockId");

                    b.Navigation("Order");

                    b.Navigation("ProductItem");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.OrderProductItemBundle", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Order", "Order")
                        .WithMany("OrderProductItemBundles")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderJoinProductItemBundle_OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItemBundle", "ProductItemBundle")
                        .WithMany("OrderProductItemBundle")
                        .HasForeignKey("ProductItemBundleId")
                        .HasConstraintName("FK_OrderJoinProductItemBundle_ProductItemBundleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductItemBundle");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("Digital_Services_BD.Models.PaymentTransaction", "OrderId")
                        .HasConstraintName("FK_PaymentTransaction_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductCategoryJoinProductGroup", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductCategory", "ProductCategory")
                        .WithMany("ProductCategoryJoinProductGroup")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_ProductCategoryJoinProductGroup_ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductGroup", "ProductGroup")
                        .WithMany("ProductCategoryJoinProductGroup")
                        .HasForeignKey("ProductGroupId")
                        .HasConstraintName("FK_ProductCategoryJoinProductGroup_ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemBundleJoinProductItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItemBundle", "ProductItemBundle")
                        .WithMany("ProductItemBundleJoinProductItem")
                        .HasForeignKey("ProductItemBundleId")
                        .HasConstraintName("FK_ProductItemBundleJoinProductItem_ProductItemBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemBundleJoinProductItem")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemBundleJoinProductItem_ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductItem");

                    b.Navigation("ProductItemBundle");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemCustomField", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemCustomFields")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemCustomField_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemFeature", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", null)
                        .WithOne("ProductItemFeature")
                        .HasForeignKey("Digital_Services_BD.Models.ProductItemFeature", "ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinProductCategory", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductCategory", "ProductCategory")
                        .WithMany("ProductItemJoinProductCategory")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_ProductItemJoinProductCategory_ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemJoinProductCategory")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemJoinProductCategory_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinPromoOffer", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemJoinPromoOffer")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemJoinPromoOffer_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.PromoOffer", "PromoOffer")
                        .WithMany("ProductItemJoinPromoOffer")
                        .HasForeignKey("PromoOfferId")
                        .HasConstraintName("FK_ProductItemJoinPromoOffer_PromoOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");

                    b.Navigation("PromoOffer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemJoinSearchTagProductItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemJoinSearchTagProductItem")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemJoinSearchTagProductItem_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.SearchTagProductItem", "SearchTagProductItem")
                        .WithMany("ProductItemJoinSearchTagProductItem")
                        .HasForeignKey("SearchTagProductItemId")
                        .HasConstraintName("FK_ProductItemJoinSearchTagProductItem_SearchTagProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");

                    b.Navigation("SearchTagProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemPrice", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductItemPrice")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductItemPrice_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductSectionJoinProductItem", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductSectionJoinProductItem")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductSectionJoinProductItem_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Services_BD.Models.ProductSection", "ProductSection")
                        .WithMany("ProductSectionJoinProductItem")
                        .HasForeignKey("ProductSectionId")
                        .HasConstraintName("FK_ProductSectionJoinProductItem_ProductSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");

                    b.Navigation("ProductSection");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductStock", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithMany("ProductStocks")
                        .HasForeignKey("ProductItemId")
                        .HasConstraintName("FK_ProductStock_ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductStockCount", b =>
                {
                    b.HasOne("Digital_Services_BD.Models.ProductItem", "ProductItem")
                        .WithOne("ProductStockCount")
                        .HasForeignKey("Digital_Services_BD.Models.ProductStockCount", "ProductItemId")
                        .HasConstraintName("FK_ProductStockCount_ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Carousel", b =>
                {
                    b.Navigation("CarouselJoinCarouselImage");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CartProductItemBundles");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Deliverable", b =>
                {
                    b.Navigation("DeliverableBundles");

                    b.Navigation("DeliverableItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.DeliverableBundle", b =>
                {
                    b.Navigation("DeliverableBundleItems");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Order", b =>
                {
                    b.Navigation("Deliverable");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderProductItemBundles");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.OrderItem", b =>
                {
                    b.Navigation("DeliverableItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductCategory", b =>
                {
                    b.Navigation("ProductCategoryJoinProductGroup");

                    b.Navigation("ProductItemJoinProductCategory");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductGroup", b =>
                {
                    b.Navigation("ProductCategoryJoinProductGroup");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItem", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ProductItemBundleJoinProductItem");

                    b.Navigation("ProductItemCustomFields");

                    b.Navigation("ProductItemFeature");

                    b.Navigation("ProductItemJoinProductCategory");

                    b.Navigation("ProductItemJoinPromoOffer");

                    b.Navigation("ProductItemJoinSearchTagProductItem");

                    b.Navigation("ProductItemPrice");

                    b.Navigation("ProductSectionJoinProductItem");

                    b.Navigation("ProductStockCount");

                    b.Navigation("ProductStocks");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductItemBundle", b =>
                {
                    b.Navigation("CartProductItemBundle");

                    b.Navigation("OrderProductItemBundle");

                    b.Navigation("ProductItemBundleJoinProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductSection", b =>
                {
                    b.Navigation("ProductSectionJoinProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.ProductStock", b =>
                {
                    b.Navigation("DeliverableBundleItem");

                    b.Navigation("DeliverableItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.PromoOffer", b =>
                {
                    b.Navigation("ProductItemJoinPromoOffer");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.SearchTagProductItem", b =>
                {
                    b.Navigation("ProductItemJoinSearchTagProductItem");
                });

            modelBuilder.Entity("Digital_Services_BD.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
